### ISSUE TITLE
What version should this gem be?

### ISSUE THREAD

**Issue by thisMagpie** [thisMagpie/fftw#13]
I am not sure what version this gem should be or how often to bump it.

I think it would be useful and informative if I were to start making use of the milestones feature on github issue tracker to indicate when milestones have been reached. 

@cjfuller what do you think?

**Comment by cjfuller** [comment]
I usually start with 0.0.1, and semantic version (as referenced in that other issue) up from there, bumping the number appropriately whenever I want to package it into a gem and push it to rubygems.

Hence, I'm usually on 0.0.1 for a good long while!

**Comment by thisMagpie** [comment]
@cjfuller should it not be on 1.0.0 if it's ready to package to a gem? I ask because the guide suggests versions < 1.0.0 are unstable => development versions so I was kind aiming to release with 1.0.0 but I see a lot of gems out there which aren't doing that so maybe I am missing something?

So far, I have mainly been bumping just when I changed a dependency by removing or taking it out but other than that I have not been sure what landmarks to apply to bumps to see they are applied with clear consistency.

I took the rcX part out because I was not sure when that would apply so I wasn't likely to bump it in that case anyway. I'll take another look at the document and see if it's worth using that now things are further along though. Should I close this or leave it open?

**Comment by cjfuller** [comment]
Sure, 1.0.0 is reasonable when you're ready to package it.

I think a common expectation is that if you have something that's version >= 1.0.0, you can depend on the interface to that library not breaking until the next major release, whereas < 1.0.0, things may still be changing rapidly.  So if you're pretty satisfied that you're not going to remove any interface methods, or break how they behave for a while, then 1.0.0 is a good number.

**Comment by thisMagpie** [comment]
Ok I will close this in that case then. Feel free to open a new one if you spot any problems in the versioning used though. Thanks.
