### ISSUE TITLE
Complex Number data type

### ISSUE THREAD

**Issue by thisMagpie** [thisMagpie/fftw#14]
[See this discussion on fftw complex numbers](http://www.fftw.org/doc/Complex-numbers.html#Complex-numbers)

NMatrix has its own dtype for complex numbers so whether to prioritise using this or not is probably a consideration here too.

**Comment by translunar** [comment]
Per that discussion, NMatrix's complex type is fully storage-compatible with C99 and C++ STL.

**Comment by thisMagpie** [comment]
@mohawkjohn thus far I had been working with just C and ruby so I am not sure how to use the information on c++ in this case. Do you think I this approach is likely to be problematic for me?

Aside from that query, I am still a bit unclear on the advantage of the complex type in nmatrix over the one that comes with the standard ruby install for example, so I am wondering about that a little.

 @cjfuller do you have any thoughts to shar eon this, too?

**Comment by cjfuller** [comment]
With respect to the ruby complex type, I suspect that is a pure ruby implementation and not the way to go.

It looks like FFTW, NMatrix, C99, and the C++ stl all use binary-compatible complex number implementations, so I think you can just cast between them as needed.

**Comment by cjfuller** [comment]
After checking the source, the complex number type in the standard library claims to be deprecated, so definitely don't go that route.

**Comment by translunar** [comment]
For the purposes of how data are stored and processed, you can think of C++ as being identical to C.
