### ISSUE TITLE
Needless #ifdef statement

### ISSUE THREAD

**Issue by domitry** [thisMagpie/fftw#15]
I generally read your code and had some little questions. I found lines below in fftw/include/fftw.h.

``` C
#ifdef RUBY_1_9_LATER
#include "ruby/io.h"
#else
#include "ruby/io.h"
#endif
```

I cannot find the difference between those two cases, but is this statement have some meaning?

**Comment by thisMagpie** [comment]
Thanks for spotting that!

Fixed it with https://github.com/thisMagpie/fftw/commit/dce3da68ba1f38a6a8f7839b924828f6f0163c19 since there was not much else to do but that, I imagine. 

Much appreciated.
