### ISSUE TITLE
About ChangeLog

### ISSUE THREAD

**Issue by domitry** [thisMagpie/fftw#16]
I read fftw/ChangeLog, but it seems not to be updated since 2009. This is only a question, but are you planning to add new lines to that file, or clean up history and write new one?

**Comment by thisMagpie** [comment]
Thanks for raising this. It relates to [another issue](https://github.com/thisMagpie/fftw/issues/13) too,  because actually, I am not sure how regularly to bump versions or what to make the start point, since the repo is pretty unrecognisable from what it used to be before I cloned it. I have now changed its name, too so I am not really sure how to approach it. Do you have any suggestions?

**Comment by domitry** [comment]
Hmm, actually I'm new to OSS project and I do not know a custom, but I found text below in Wikipedia.

> Forks often restart version numbering from 0.1 or 1.0 even if the original software was at version 3.0, 4.0, or 5.0. An exception is when the forked software is designed to be a drop-in replacement for the original project, e.g. MariaDB for MySQL[15] or LibreOffice for OpenOffice.org.
> (quote from http://en.wikipedia.org/wiki/Fork_(software_development)#Forking_of_free_and_open_source_software)

So I think restarting numbering is the better solution.

**Comment by agarie** [comment]
I agree with @domitry. When choosing version numbers, you could try something similar to [Semantic Versioning](http://semver.org/). :)

**Comment by cjfuller** [comment]
+1 for semantic versioning.  Some of the ruby toolchain assumes that you use it (e.g. bundler), so probably best to go with that.

**Comment by thisMagpie** [comment]
Thanks guys! This is useful. I had already bumped it to 0.0.2, the original went to 0.3.0 I think. Either way, I dread to imagine how to articulate what happened between any of those milestones! 

Accordingly, I will reset to 0.0.1 and add my next changes as 0.0.2 so I can note them in the changelog this time around as long as that makes sense to everyone?

**Comment by thisMagpie** [comment]
I think this is safe to close now but it's worth seeing what @domitry thinks of the new changelog first, if that is alright with you @domitry? Please let me know what you think. Thanks.

**Comment by domitry** [comment]
Hi, I looked at ChangeLog of now. I felt that it contains a bit too many lines, but I think it is not a big deal. I'm looking forward to seeing the version 1.0.0!

**Comment by thisMagpie** [comment]
thanks @domitry fyi I generated it with the following command:

```
git log --oneline > Changelog 
```
