### ISSUE TITLE
Minor changes to README.md

### ISSUE THREAD

**Issue by agarie** [thisMagpie/fftw#21]
The README suffix should be changed to `md` in order to use markdown processing correctly. E.g. some links aren't being presented as intended, some code formatting is incorrect, but nothing critical. :P

Keep up the good work!

**Comment by thisMagpie** [comment]
@agarie, what do you think of [the changes](https://github.com/thisMagpie/fftw/blob/master/README.md)? [I left the rdoc version in](https://github.com/thisMagpie/fftw/blob/master/README.rdoc), because I think the generated rdocs might want it, but I can take that file out if it doesn't matter.
