### ISSUE TITLE
nmatrix spec should raise an error 

### ISSUE THREAD

**Issue by thisMagpie** [thisMagpie/fftw#9]
nmatrix spec [should raise an error when the rank is out of bounds](https://travis-ci.org/thisMagpie/fftw/jobs/26963177#L247) but it does not. Oddly, this actually does not seem to have any problems on my local machine so I am a bit baffled. Dodgy .travis.yml
@cjfuller what do you think?

**Comment by cjfuller** [comment]
I think this was a bug that was fixed but may not have been released in the gem version yet.  see: https://github.com/SciRuby/nmatrix/issues/227
